// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';
import { CapacitorStorage } from '@capacitor/storage';

const SUPABASE_URL = "https://ighllleypgbkluhcihvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnaGxsbGV5cGdia2x1aGNpaHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDg0MzIsImV4cCI6MjA3MTI4NDQzMn0.32KpEBVd6go9HUpd5IzlaKz2dTai0TqGn9P9Xqqkv2E";

// Custom storage adapter for mobile
const customStorage = Capacitor.isNativePlatform() ? {
  getItem: async (key: string) => {
    const result = await CapacitorStorage.get({ key });
    return result.value;
  },
  setItem: async (key: string, value: string) => {
    await CapacitorStorage.set({ key, value });
  },
  removeItem: async (key: string) => {
    await CapacitorStorage.remove({ key });
  },
} : localStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});